Develop io
cliff-bielinski/space-invaders-8080-emulator pull request #50
Opened 2023-05-29 21:15 UTC by hortonau

Plugged in io and made changes to process per instruction instead of using while loop

2023-05-29 21:26 UTC, cliff-bielinski approved these changes

2023-05-30 02:42 UTC, flatherz requested changes

2023-05-30 02:42 UTC, flatherz commented on emulator.h
> +  bool colored_screen;
I guess we can leave this in for now though not sure we'll get to it. Don't need to remove for my approval but would be good to take this out if we don't get to it.

2023-05-30 02:42 UTC, flatherz commented on shell.c
> +          exit(1);
Do we want this to exit with an error code? Is this not the normal exit condition?

2023-05-30 02:50 UTC, flatherz approved these changes

2023-05-30 02:51 UTC, merged